export enum SettingsStorage {
    JIRA_USER = "JIRA_USER",
    JIRA_TOKEN = "JIRA_TOKEN",
    JIRA_PREFIX = "JIRA_PREFIX",
    TOGGL_TOKEN = "TOGGL_TOKEN",
    FREE_TASK_KEY = "FREE_TASK_KEY",
    FREE_TASK_TAG = "FREE_TASK_TAG"
}