export enum SettingsStorage {
    JIRA_USER = "JIRA_USER",
    JIRA_TOKEN = "JIRA_TOKEN",
    JIRA_PREFIX = "JIRA_PREFIX",
    TOGGL_TOKEN = "TOGGL_TOKEN",
    JIRA_TASKS_ALLOWED_PREFIXES = "JIRA_TASKS_ALLOWED_PREFIXES"
}